spring.application.name=reactivo

# Configuración de la base de datos MariaDB
spring.r2dbc.url=r2dbc:mariadb://localhost:3306/my_database
spring.r2dbc.username=my_user
spring.r2dbc.password=my_user_password

# Configuración del cliente JDBC (opcional, para herramientas de administración)
spring.datasource.url=jdbc:mariadb://localhost:3306/my_database
spring.datasource.username=my_user
spring.datasource.password=my_user_password


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.override-with-generic-response=false
springdoc.api-docs.version=OPENAPI_3_0