spring.application.name=reactivo

# Configuración Reactiva R2DBC (Usada por Spring Data / WebFlux)
spring.r2dbc.url=r2dbc:mariadb://localhost:3306/my_database
spring.r2dbc.username=my_user
spring.r2dbc.password=my_user_password

# Configuración JDBC Bloqueante (Usada ÚNICAMENTE por Flyway)
spring.flyway.enabled=true
spring.flyway.url=jdbc:mariadb://localhost:3306/my_database
spring.flyway.user=my_user
spring.flyway.password=my_user_password
spring.flyway.locations=classpath:db/migration

# Configuración de Springdoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.override-with-generic-response=false
springdoc.api-docs.version=OPENAPI_3_0